name: mandarin_indo_app
description: Aplikasi Belajar Bahasa Mandarin.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  intl: ^0.18.0
  google_fonts: ^3.0.1
  flutter_sticky_widgets: ^0.0.3
  equatable: ^2.0.5
  url_launcher: ^6.1.8
  pull_to_refresh_flutter3: ^2.0.1
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16
  flutter_swiper_plus: ^2.0.4
  shared_preferences: ^2.0.17
  dropdown_button2: ^1.9.2
  get: ^4.6.5
  auto_size_text: ^3.0.0
  flutter_beep: ^1.0.0
  countdown_progress_indicator: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/data/kosakata1.json
    - assets/data/kosakata2.json
    - assets/data/kosakata3.json
    - assets/data/kosakata4.json
    - assets/data/kosakata5.json
    - assets/data/kosakata6.json
    - assets/data/kosakata7.json
    - assets/data/kosakata8.json
    - assets/data/kosakata9.json
    - assets/data/kosakata10.json

    - assets/data/kosakata11.json
    - assets/data/kosakata12.json
    - assets/data/kosakata13.json
    - assets/data/kosakata14.json
    - assets/data/kosakata15.json
    - assets/data/kosakata16.json
    - assets/data/kosakata17.json
    - assets/data/kosakata18.json
    - assets/data/kosakata19.json
    - assets/data/kosakata20.json

    - assets/data/kosakata21.json
    - assets/data/kosakata22.json
    - assets/data/kosakata23.json
    - assets/data/kosakata24.json
    - assets/data/kosakata25.json
    - assets/data/kosakata26.json
    - assets/data/kosakata27.json
    - assets/data/kosakata28.json
    - assets/data/kosakata29.json
    - assets/data/kosakata30.json
    - assets/data/kosakata20000.json

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/lmilogo.jpg"
